/**
 * TaskFlow API Server
 * =====================================================
 * STAGE 2 OUTPUT — Generated by IDE AI from api_spec.json
 *
 * This Express.js server was scaffolded by reading the
 * OpenAPI 3.0 spec produced in Stage 1 (Chat AI) and
 * auto-generating route handlers, validation schemas,
 * and an in-memory data store.
 * =====================================================
 */

const express = require("express");
const cors = require("cors");
const taskRoutes = require("./routes/tasks");

const app = express();
const PORT = process.env.PORT || 3000;

// Middleware
app.use(cors());
app.use(express.json());

// Health check
app.get("/api/health", (req, res) => {
  res.json({ status: "ok", timestamp: new Date().toISOString() });
});

// Mount routes derived from OpenAPI spec paths
app.use("/api/tasks", taskRoutes);

// Global error handler
app.use((err, req, res, next) => {
  console.error(err.stack);
  res.status(500).json({
    error: "InternalServerError",
    message: "An unexpected error occurred",
  });
});

// Start server (only when not in test mode)
if (process.env.NODE_ENV !== "test") {
  app.listen(PORT, () => {
    console.log(`TaskFlow API running on http://localhost:${PORT}`);
  });
}

module.exports = app;
