/**
 * Joi Validation Schemas
 * =====================================================
 * STAGE 2 OUTPUT — Generated by IDE AI from api_spec.json
 *
 * These validation schemas mirror the OpenAPI component
 * schemas (CreateTaskInput, UpdateTaskInput) from Stage 1.
 * =====================================================
 */

const Joi = require("joi");

const VALID_STATUSES = ["pending", "in_progress", "completed"];
const VALID_PRIORITIES = ["low", "medium", "high", "critical"];

/**
 * Schema for POST /tasks — CreateTaskInput
 * Derived from: components.schemas.CreateTaskInput
 */
const createTaskSchema = Joi.object({
  title: Joi.string().min(1).max(200).required().messages({
    "string.empty": "Title cannot be empty",
    "string.max": "Title cannot exceed 200 characters",
    "any.required": "Title is required",
  }),
  description: Joi.string().max(2000).allow("").optional(),
  priority: Joi.string()
    .valid(...VALID_PRIORITIES)
    .optional()
    .default("medium"),
  assignee: Joi.string()
    .email()
    .optional()
    .messages({ "string.email": "Assignee must be a valid email" }),
  dueDate: Joi.date()
    .iso()
    .optional()
    .messages({ "date.format": "Due date must be a valid ISO 8601 date" }),
});

/**
 * Schema for PUT /tasks/:taskId — UpdateTaskInput
 * Derived from: components.schemas.UpdateTaskInput
 */
const updateTaskSchema = Joi.object({
  title: Joi.string().min(1).max(200).optional(),
  description: Joi.string().max(2000).allow("").optional(),
  status: Joi.string()
    .valid(...VALID_STATUSES)
    .optional(),
  priority: Joi.string()
    .valid(...VALID_PRIORITIES)
    .optional(),
  assignee: Joi.string().email().allow(null).optional(),
  dueDate: Joi.date().iso().allow(null).optional(),
})
  .min(1)
  .messages({
    "object.min": "At least one field must be provided for update",
  });

/**
 * Query parameter validation for GET /tasks
 * Derived from: paths./tasks.get.parameters
 */
const listTasksQuerySchema = Joi.object({
  status: Joi.string()
    .valid(...VALID_STATUSES)
    .optional(),
  priority: Joi.string()
    .valid(...VALID_PRIORITIES)
    .optional(),
});

module.exports = {
  createTaskSchema,
  updateTaskSchema,
  listTasksQuerySchema,
  VALID_STATUSES,
  VALID_PRIORITIES,
};
