/**
 * TaskFlow API — Integration Test Suite
 * =====================================================
 * STAGE 3 OUTPUT — Generated by CLI AI from source code
 *
 * These tests were auto-generated by analyzing the route
 * handlers in routes/tasks.js and validation schemas in
 * validation.js. Each test case covers:
 *   - Happy path for each CRUD operation
 *   - Validation error paths (from Joi schemas)
 *   - Edge cases (404s, empty payloads, filtering)
 * =====================================================
 */

const request = require("supertest");
const app = require("../server");
const taskRoutes = require("../routes/tasks");

// Reset in-memory store before each test
beforeEach(() => {
  taskRoutes._tasks.clear();
});

describe("TaskFlow API — Auto-Generated Tests", () => {
  // ──────────────────────────────────────────────
  // Health Check
  // ──────────────────────────────────────────────
  describe("GET /api/health", () => {
    it("should return health status", async () => {
      const res = await request(app).get("/api/health");
      expect(res.status).toBe(200);
      expect(res.body).toHaveProperty("status", "ok");
      expect(res.body).toHaveProperty("timestamp");
    });
  });

  // ──────────────────────────────────────────────
  // POST /api/tasks — createTask
  // ──────────────────────────────────────────────
  describe("POST /api/tasks", () => {
    it("should create a task with only a title (minimum valid input)", async () => {
      const res = await request(app)
        .post("/api/tasks")
        .send({ title: "My First Task" });

      expect(res.status).toBe(201);
      expect(res.body).toMatchObject({
        title: "My First Task",
        status: "pending",
        priority: "medium",
        description: "",
      });
      expect(res.body).toHaveProperty("id");
      expect(res.body).toHaveProperty("createdAt");
    });

    it("should create a task with all fields populated", async () => {
      const res = await request(app).post("/api/tasks").send({
        title: "Complete Report",
        description: "Finish the Q4 financial report",
        priority: "high",
        assignee: "alice@example.com",
        dueDate: "2026-03-01T12:00:00Z",
      });

      expect(res.status).toBe(201);
      expect(res.body.priority).toBe("high");
      expect(res.body.assignee).toBe("alice@example.com");
    });

    it("should return 400 when title is missing", async () => {
      const res = await request(app)
        .post("/api/tasks")
        .send({ description: "No title provided" });

      expect(res.status).toBe(400);
      expect(res.body.error).toBe("ValidationError");
    });

    it("should return 400 when title exceeds 200 characters", async () => {
      const res = await request(app)
        .post("/api/tasks")
        .send({ title: "A".repeat(201) });

      expect(res.status).toBe(400);
      expect(res.body.error).toBe("ValidationError");
    });

    it("should return 400 for invalid priority value", async () => {
      const res = await request(app)
        .post("/api/tasks")
        .send({ title: "Test", priority: "urgent" });

      expect(res.status).toBe(400);
      expect(res.body.error).toBe("ValidationError");
    });

    it("should return 400 for invalid assignee email", async () => {
      const res = await request(app)
        .post("/api/tasks")
        .send({ title: "Test", assignee: "not-an-email" });

      expect(res.status).toBe(400);
      expect(res.body.error).toBe("ValidationError");
    });
  });

  // ──────────────────────────────────────────────
  // GET /api/tasks — listTasks
  // ──────────────────────────────────────────────
  describe("GET /api/tasks", () => {
    it("should return an empty array when no tasks exist", async () => {
      const res = await request(app).get("/api/tasks");
      expect(res.status).toBe(200);
      expect(res.body).toEqual([]);
    });

    it("should return all tasks", async () => {
      await request(app).post("/api/tasks").send({ title: "Task 1" });
      await request(app).post("/api/tasks").send({ title: "Task 2" });

      const res = await request(app).get("/api/tasks");
      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(2);
    });

    it("should filter tasks by status", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Task 1" });
      await request(app)
        .put(`/api/tasks/${created.body.id}`)
        .send({ status: "completed" });
      await request(app).post("/api/tasks").send({ title: "Task 2" });

      const res = await request(app).get("/api/tasks?status=completed");
      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(1);
      expect(res.body[0].status).toBe("completed");
    });

    it("should filter tasks by priority", async () => {
      await request(app)
        .post("/api/tasks")
        .send({ title: "Low", priority: "low" });
      await request(app)
        .post("/api/tasks")
        .send({ title: "High", priority: "high" });

      const res = await request(app).get("/api/tasks?priority=high");
      expect(res.status).toBe(200);
      expect(res.body).toHaveLength(1);
      expect(res.body[0].priority).toBe("high");
    });

    it("should return 400 for invalid query parameter", async () => {
      const res = await request(app).get("/api/tasks?status=invalid_status");
      expect(res.status).toBe(400);
    });
  });

  // ──────────────────────────────────────────────
  // GET /api/tasks/:taskId — getTask
  // ──────────────────────────────────────────────
  describe("GET /api/tasks/:taskId", () => {
    it("should return a task by ID", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Find Me" });

      const res = await request(app).get(`/api/tasks/${created.body.id}`);
      expect(res.status).toBe(200);
      expect(res.body.title).toBe("Find Me");
    });

    it("should return 404 for non-existent task", async () => {
      const res = await request(app).get("/api/tasks/non-existent-id");
      expect(res.status).toBe(404);
      expect(res.body.error).toBe("NotFound");
    });
  });

  // ──────────────────────────────────────────────
  // PUT /api/tasks/:taskId — updateTask
  // ──────────────────────────────────────────────
  describe("PUT /api/tasks/:taskId", () => {
    it("should update a task title", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Original Title" });

      const res = await request(app)
        .put(`/api/tasks/${created.body.id}`)
        .send({ title: "Updated Title" });

      expect(res.status).toBe(200);
      expect(res.body.title).toBe("Updated Title");
    });

    it("should update task status to completed", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Do Something" });

      const res = await request(app)
        .put(`/api/tasks/${created.body.id}`)
        .send({ status: "completed" });

      expect(res.status).toBe(200);
      expect(res.body.status).toBe("completed");
      expect(new Date(res.body.updatedAt).getTime()).toBeGreaterThanOrEqual(
        new Date(res.body.createdAt).getTime(),
      );
    });

    it("should return 404 when updating non-existent task", async () => {
      const res = await request(app)
        .put("/api/tasks/fake-id")
        .send({ title: "Ghost" });

      expect(res.status).toBe(404);
    });

    it("should return 400 when update body is empty", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Test" });

      const res = await request(app)
        .put(`/api/tasks/${created.body.id}`)
        .send({});

      expect(res.status).toBe(400);
      expect(res.body.error).toBe("ValidationError");
    });

    it("should return 400 for invalid status value", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Test" });

      const res = await request(app)
        .put(`/api/tasks/${created.body.id}`)
        .send({ status: "archived" });

      expect(res.status).toBe(400);
    });
  });

  // ──────────────────────────────────────────────
  // DELETE /api/tasks/:taskId — deleteTask
  // ──────────────────────────────────────────────
  describe("DELETE /api/tasks/:taskId", () => {
    it("should delete a task and return 204", async () => {
      const created = await request(app)
        .post("/api/tasks")
        .send({ title: "Delete Me" });

      const res = await request(app).delete(`/api/tasks/${created.body.id}`);
      expect(res.status).toBe(204);

      // Confirm it is gone
      const check = await request(app).get(`/api/tasks/${created.body.id}`);
      expect(check.status).toBe(404);
    });

    it("should return 404 when deleting non-existent task", async () => {
      const res = await request(app).delete("/api/tasks/ghost-id");
      expect(res.status).toBe(404);
    });
  });
});
